# Generated by Django 5.2.4 on 2025-07-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
    ]
